# Generated by Django 6.0.3 on 2026-03-26 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategorija",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv", models.CharField(max_length=100)),
                ("opis", models.TextField(blank=True, null=True)),
                (
                    "boja",
                    models.CharField(
                        default="#000000",
                        help_text="HEX vrednost boje za UI",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "kategorije",
            },
        ),
        migrations.CreateModel(
            name="Obaveza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naslov", models.CharField(max_length=100)),
                ("opis", models.TextField(blank=True, null=True)),
                ("kreirano", models.DateTimeField(auto_now_add=True)),
                (
                    "rok_za_zavrsetak",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("zavrseno", models.BooleanField(default=False)),
                (
                    "prioritet",
                    models.CharField(
                        choices=[("N", "Nizak"), ("Srednji", "S"), ("V", "Visok")],
                        default="S",
                        max_length=7,
                    ),
                ),
                (
                    "kategorija",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obaveze",
                        to="task.kategorija",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Obaveze",
            },
        ),
    ]
