# Generated by Django 6.0.4 on 2026-04-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="obaveza",
            name="slika",
            field=models.ImageField(blank=True, null=True, upload_to="obaveze/"),
        ),
        migrations.AlterField(
            model_name="obaveza",
            name="prioritet",
            field=models.CharField(
                choices=[("Nizak", "N"), ("S", "Srednji"), ("Visok", "V")],
                default="S",
                max_length=7,
            ),
        ),
    ]
